[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "csecg"
version = "0.0.0"
description = "ECG Compressed Sensing - ECE537 Final Project"
requires-python = ">=3.14"
authors = [
    {name = "Jordan Schott", email = "jschott515@gmail.com"},
]
dependencies = [
    "flake8>=7.3",
    "flake8-pyproject>=1.2",
    "isort>=7.0",
    "wfdb>=4.3",
    "numpy>=2.4",
    "matplotlib>=3.10",
    "cvxpy>=1.8",
]

[tool.flake8]
max-line-length = 120

[tool.isort]
profile = "black"
line_length = 120
